version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: simulasi
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist data in a named volume
  application:
    image: python:3

volumes:
  pgdata:
